# Generated by Django 4.2.24 on 2025-09-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=50)),
                ('detalhes', models.TextField(blank=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('imagem', models.ImageField(upload_to='carros/')),
            ],
            options={
                'ordering': ['modelo'],
            },
        ),
    ]
